### ISSUE TITLE
Finish Head Segmentation

### ISSUE THREAD

**Issue by allywarner** [allywarner/BrainSegmentation#1]
-Finish working on the mouth by hand (paintbrush). 
  -Look sagittally if it isn't looking great.
  -Boolean OR to combine them.

-Fill in the dimples and holes (using fill holes or paintbrush). Try not to use paintbrush if you don't have to!

-Document what Jess did in the pipeline so we don't forget and so that somebody else can reproduce! 👍

**Comment by andycorb** [comment]
I worked on paintbrushing the mouth. I think looks okay, not great. I seem to be at the point that the more I paint the worse it looks. 

I filled in the dimples and holes on the skin.

**Comment by allywarner** [comment]
Do boolean OR to combine mouth and head.
Pipeline documentation.
Leaving holes in the bottom until after bones are done.

**Comment by allywarner** [comment]
Scalp layer of segmentation has been completed. We were able to get a top lip out of the missing mouth section.
